apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBMzO0NuaCx4L58+0HcZKw8Ro11uS3hqAhc4Qs/OTZpl1We9ffgYpZaJqBTWBLPFylwYLGCop1oE9AlKyAIGJCWnn7JE+eUfqGbjqfEh1YteN1/Xg/4XURHJKjM7K5t+4cFBZKuDGowkqr4tvpBi8jMPbv/G40XwrojC3pXpBkVnVniKESLAD1ad7uI7O6IwSbDKi8phlg97IkqUTUlg6rxTd1+ySCz/pe8S7YZmQ7MxLq3oxk+sw34kIH/+fyTgTNlzcRQEgCCkW7VlTaaDFazq5+2bOgolysLcTSITRfae5AFfDS51UsNs4c12efq/B51tiW+aTSVY92DifUzo0cFOL7AtKRmhE+IJHwgfMshzT+SqaeVYY8YvEeChyvdvUgYqILLjlilLN5M8sl4S/ZQIBI5g9q6hr8k6TlajyIFlfdA8WtmlM4zS8MBAki+14Pm037lE980dwVlfjkcOoYFY3K5K/kdwp9YWz/gEct3wYKc9cUSiDEzcVErE8nbDSht2aAezFHtXXqFPawQ1dq4hmT4eiI0fLm8xMRL2AthGpNDba5WxciGHYrdci/vZDpw8Z/tclnM6KEt+KjOn3B6/SvqAs68Ylx5U/WUIY9ouc6bJM/p2A4BtPzs9R/lDKa063k4F8zzw2xMZLRWWAdQoc8Dd5Q/D/ugg/F+7+C85C/DzMrZJonX8ppyL/36a8PyHnz9sLBEQV4=
    username: AgA6uY6Ut/pMpg7SLDIWj4m+fQWiHS+c3NzMB7GvVbnAAgysOL0pxMpQeyaLtRw6lfzMdWX5Net54RL8/bLA6WW6MgqFvwe5vvTvTluSrS6OKriqR/ewAsfeCrEXcgHEcg1vPYe9uLf39Q0JVQ9Lglw3jzb0RqyaO2nL2LIizTwczmCu49AOjP2UC2v1aI8C16n/O2m5cJJzC1DWLMouWKJUMRya3UGuRY5oKykI4T/GCYQvkGvDhsfDjjGs/1iHWh7ry+mFUPYdEf7jDaaOZ8MqhUX7HONDQQ471w0+rI1NdR2gYoGylXleYwIb5knepLWLfE3pejPDmxI45y7x4DxzsJuUp8hTPfwnydR8QTUn8f+p+yEeVRd+M7CcgES6s/Bbb7/NcomLTzkvHDy1dhgGDUuYdNCfu9kduGcK+CXM+kN1vMUVy+xO/zwI7WfvA31k62pzzfaaB3Pl+Qt/5XzpNOH6g/qr7j58DhoPlHKbWGTosi6SVHPIGZSBXMmpF/P9xAKmEzKJEkHZm7aYoWe2mtO9o1V6oVyzUBOqwt1QfFhq2qROM4kuLWFt9m3dcZWs5AMQdfAf8BglAMNzTB2qylv3kh3Jomgi6uj/47HurBI44LVcodZRTV+4PJGGsUs+VbyA4rSX1se84pT1mlxuKRYMKaZdEIkm7fGx6TVj09bQYtizqbKb2z81xsc7GynaORmnLA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

